FROM rocker/rstudio:latest
MAINTAINER kgosik@broadinstitute.org

#########
### Install Utilities
#########
RUN apt-get update && apt-get install -y gcc g++ perl python python3 automake make cmake less vim \
                                       wget git curl bsdtar libdb-dev libglu1-mesa-dev \
                                       zlib1g-dev bzip2 libncurses5-dev \
                                       texlive-latex-base \
                                       default-jre \
                                       python-pip python3-pip python-dev \
                                       gfortran \
                                       build-essential libghc-zlib-dev libncurses-dev libbz2-dev liblzma-dev libpcre3-dev libxml2-dev \
                                       libblas-dev gfortran git unzip ftp libzmq3-dev nano ftp fort77 libreadline-dev \
                                       libcurl4-openssl-dev libx11-dev libxt-dev \
                                       x11-common libcairo2-dev libpng-dev libreadline6-dev libjpeg-dev pkg-config \
                                       build-essential cmake gsl-bin libgsl0-dev libeigen3-dev libboost-all-dev \
                                       libssl-dev libssl-dev libcairo2-dev libxt-dev libgtk2.0-dev libcairo2-dev xvfb xauth xfonts-base \
                                       apt-transport-https libhdf5-serial-dev

RUN cp $(which tar) $(which tar)~ \
    && ln -sf $(which bsdtar) $(which tar)

## Install R packages
COPY install.R /usr/local/src
## install necessary R packages
RUN Rscript /usr/local/src/install.R

## Install Python Requirements
COPY requirements.txt /usr/local/src
RUN pip3 install -r /usr/local/src/requirements.txt
